language: python
python:
  - "3.7"

dist: xenial

os:
  - linux
#   - osx

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "xufan6"
  - git config --local user.email "xufan6@gmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

# command to install dependencies 
install:
  - pip install pyinstaller

# command to run tests
script:
  - sed -i -e "s/\${BUILD_SOURCEBRANCHNAME}/${TRAVIS_BRANCH}/" -e "s/\${BUILD_DATE}/$(date --iso-8601=seconds)/" run.py
  - cp /etc/ssl/certs/ca-certificates.crt cert.pem
  - export SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
  - pyinstaller --onefile --noconfirm --add-data "cert.pem:lib" --clean ./.build/ddns.spec
  - ./dist/ddns || test -e "config.json"

git:
  depth: 2

deploy:
  - provider: releases
    api_key: "${GH_TOKEN}"
    skip_cleanup: true
    file:
      - "dist/ddns"
    draft: true
    on:
      all_branches: true
